enum TypeEnum {
	Bug = 'Bug',
	Dark = 'Dark',
	Dragon = 'Dragon',
	Electric = 'Electric',
	Fairy = 'Fairy',
	Fighting = 'Fighting',
	Fire = 'Fire',
	Flying = 'Flying',
	Ghost = 'Ghost',
	Grass = 'Grass',
	Ground = 'Ground',
	Ice = 'Ice',
	Normal = 'Normal',
	Poison = 'Poison',
	Psychic = 'Psychic',
	Rock = 'Rock',
	Steel = 'Steel',
	Water = 'Water',
}

type Type = {
	name: TypeEnum;
	matchup: Matchup;
};

type Matchup = {
	offense: {
		double: string[];
		immune: string[];
		normal: string[];
		resisted: string[];
	};
	defense: {
		double: string[];
		immune: string[];
		normal: string[];
		resisted: string[];
	};
};

export const Types: Type[] = [
	{
		name: TypeEnum.Bug,
		matchup: {
			offense: {
				double: ['dark', 'grass', 'psychic'],
				immune: [],
				normal: [
					'bug',
					'dragon',
					'electric',
					'ground',
					'ice',
					'normal',
					'rock',
					'water',
				],
				resisted: [
					'fairy',
					'fighting',
					'fire',
					'flying',
					'ghost',
					'poison',
					'steel',
				],
			},
			defense: {
				double: ['fire', 'flying', 'rock'],
				immune: [],
				normal: [
					'bug',
					'dark',
					'dragon',
					'electric',
					'fairy',
					'ghost',
					'ice',
					'normal',
					'poison',
					'psychic',
					'steel',
					'water',
				],
				resisted: ['fighting', 'grass', 'ground'],
			},
		},
	},
	{
		name: TypeEnum.Dark,
		matchup: {
			offense: {
				double: ['ghost', 'psychic'],
				immune: [],
				normal: [
					'bug',
					'dragon',
					'electric',
					'fire',
					'flying',
					'grass',
					'ground',
					'ice',
					'normal',
					'poison',
					'rock',
					'steel',
					'water',
				],
				resisted: ['dark', 'fairy', 'fighting'],
			},
			defense: {
				double: ['bug', 'fairy', 'fighting'],
				immune: ['psychic'],
				normal: [
					'dragon',
					'electric',
					'fire',
					'flying',
					'grass',
					'ground',
					'ice',
					'normal',
					'poison',
					'rock',
					'steel',
					'water',
				],
				resisted: ['dark', 'ghost'],
			},
		},
	},
	{
		name: TypeEnum.Dragon,
		matchup: {
			offense: {
				double: ['dragon'],
				immune: ['fairy'],
				normal: [
					'bug',
					'dark',
					'electric',
					'fighting',
					'fire',
					'flying',
					'ghost',
					'grass',
					'ground',
					'ice',
					'normal',
					'poison',
					'psychic',
					'rock',
					'water',
				],
				resisted: ['steel'],
			},
			defense: {
				double: ['dragon', 'fairy', 'ice'],
				immune: [],
				normal: [
					'bug',
					'dark',
					'fighting',
					'flying',
					'ghost',
					'ground',
					'normal',
					'poison',
					'psychic',
					'rock',
					'steel',
				],
				resisted: ['electric', 'fire', 'grass', 'water'],
			},
		},
	},
	{
		name: TypeEnum.Electric,
		matchup: {
			offense: {
				double: ['flying', 'water'],
				immune: ['ground'],
				normal: [
					'bug',
					'dark',
					'fairy',
					'fighting',
					'fire',
					'ghost',
					'ice',
					'normal',
					'poison',
					'psychic',
					'rock',
					'steel',
				],
				resisted: ['dragon', 'electric', 'grass'],
			},
			defense: {
				double: ['ground'],
				immune: [],
				normal: [
					'bug',
					'dark',
					'dragon',
					'fairy',
					'fighting',
					'fire',
					'ghost',
					'grass',
					'ice',
					'normal',
					'poison',
					'psychic',
					'rock',
					'water',
				],
				resisted: ['electric', 'flying', 'steel'],
			},
		},
	},
	{
		name: TypeEnum.Fairy,
		matchup: {
			offense: {
				double: ['dark', 'dragon', 'fighting'],
				immune: [],
				normal: [
					'bug',
					'electric',
					'fairy',
					'flying',
					'ghost',
					'grass',
					'ground',
					'ice',
					'normal',
					'psychic',
					'rock',
					'water',
				],
				resisted: ['fire', 'poison', 'steel'],
			},
			defense: {
				double: ['poison', 'steel'],
				immune: ['dragon'],
				normal: [
					'electric',
					'fairy',
					'fire',
					'flying',
					'ghost',
					'grass',
					'ground',
					'ice',
					'normal',
					'psychic',
					'rock',
					'water',
				],
				resisted: ['bug', 'dark', 'fighting'],
			},
		},
	},
	{
		name: TypeEnum.Fighting,
		matchup: {
			offense: {
				double: ['dark', 'ice', 'normal', 'rock', 'steel'],
				immune: ['ghost'],
				normal: [
					'dragon',
					'electric',
					'fighting',
					'fire',
					'grass',
					'ground',
					'water',
				],
				resisted: ['bug', 'fairy', 'flying', 'poison', 'psychic'],
			},
			defense: {
				double: ['fairy', 'flying', 'psychic'],
				immune: [],
				normal: [
					'dragon',
					'electric',
					'fighting',
					'fire',
					'ghost',
					'grass',
					'ground',
					'ice',
					'normal',
					'poison',
					'steel',
					'water',
				],
				resisted: ['bug', 'dark', 'rock'],
			},
		},
	},
	{
		name: TypeEnum.Fire,
		matchup: {
			offense: {
				double: ['bug', 'grass', 'ice', 'steel'],
				immune: [],
				normal: [
					'dark',
					'electric',
					'fairy',
					'fighting',
					'flying',
					'ghost',
					'ground',
					'normal',
					'poison',
					'psychic',
				],
				resisted: ['dragon', 'fire', 'rock', 'water'],
			},
			defense: {
				double: ['ground', 'rock', 'water'],
				immune: [],
				normal: [
					'dark',
					'dragon',
					'electric',
					'fighting',
					'flying',
					'ghost',
					'normal',
					'poison',
					'psychic',
				],
				resisted: ['bug', 'fairy', 'fire', 'grass', 'ice', 'steel'],
			},
		},
	},
	{
		name: TypeEnum.Flying,
		matchup: {
			offense: {
				double: ['bug', 'fighting', 'grass'],
				immune: [],
				normal: [
					'dark',
					'dragon',
					'fairy',
					'fire',
					'flying',
					'ghost',
					'ground',
					'ice',
					'normal',
					'poison',
					'psychic',
					'water',
				],
				resisted: ['electric', 'rock', 'steel'],
			},
			defense: {
				double: ['electric', 'ice', 'rock'],
				immune: ['ground'],
				normal: [
					'dark',
					'dragon',
					'fairy',
					'fire',
					'flying',
					'ghost',
					'normal',
					'poison',
					'psychic',
					'steel',
					'water',
				],
				resisted: ['bug', 'fighting', 'grass'],
			},
		},
	},
	{
		name: TypeEnum.Ghost,
		matchup: {
			offense: {
				double: ['ghost', 'psychic'],
				immune: ['normal'],
				normal: [
					'bug',
					'dragon',
					'electric',
					'fairy',
					'fighting',
					'fire',
					'flying',
					'grass',
					'ground',
					'ice',
					'poison',
					'rock',
					'steel',
					'water',
				],
				resisted: ['dark'],
			},
			defense: {
				double: ['dark', 'ghost'],
				immune: ['fighting', 'normal'],
				normal: [
					'dragon',
					'electric',
					'fairy',
					'fire',
					'flying',
					'grass',
					'ground',
					'ice',
					'psychic',
					'rock',
					'steel',
					'water',
				],
				resisted: ['bug', 'poison'],
			},
		},
	},
	{
		name: TypeEnum.Grass,
		matchup: {
			offense: {
				double: ['ground', 'rock', 'water'],
				immune: [],
				normal: [
					'dark',
					'electric',
					'fairy',
					'fighting',
					'ghost',
					'ice',
					'normal',
					'psychic',
				],
				resisted: [
					'bug',
					'dragon',
					'fire',
					'flying',
					'grass',
					'poison',
					'steel',
				],
			},
			defense: {
				double: ['bug', 'fire', 'flying', 'ice', 'poison'],
				immune: [],
				normal: [
					'dark',
					'dragon',
					'fairy',
					'fighting',
					'ghost',
					'normal',
					'psychic',
					'rock',
					'steel',
				],
				resisted: ['electric', 'grass', 'ground', 'water'],
			},
		},
	},
	{
		name: TypeEnum.Ground,
		matchup: {
			offense: {
				double: ['electric', 'fire', 'poison', 'rock', 'steel'],
				immune: ['flying'],
				normal: [
					'dark',
					'dragon',
					'fairy',
					'fighting',
					'ghost',
					'ground',
					'ice',
					'normal',
					'psychic',
					'water',
				],
				resisted: ['bug', 'grass'],
			},
			defense: {
				double: ['grass', 'ice', 'water'],
				immune: ['electric'],
				normal: [
					'bug',
					'dark',
					'dragon',
					'fairy',
					'fighting',
					'fire',
					'flying',
					'ghost',
					'ground',
					'normal',
					'psychic',
					'steel',
				],
				resisted: ['poison', 'rock'],
			},
		},
	},
	{
		name: TypeEnum.Ice,
		matchup: {
			offense: {
				double: ['dragon', 'flying', 'grass', 'ground'],
				immune: [],
				normal: [
					'bug',
					'dark',
					'electric',
					'fairy',
					'fighting',
					'ghost',
					'normal',
					'poison',
					'psychic',
					'rock',
				],
				resisted: ['fire', 'ice', 'steel', 'water'],
			},
			defense: {
				double: ['fighting', 'fire', 'rock', 'steel'],
				immune: [],
				normal: [
					'bug',
					'dark',
					'dragon',
					'electric',
					'fairy',
					'flying',
					'ghost',
					'grass',
					'ground',
					'normal',
					'poison',
					'psychic',
					'water',
				],
				resisted: ['ice'],
			},
		},
	},
	{
		name: TypeEnum.Normal,
		matchup: {
			offense: {
				double: [],
				immune: ['ghost'],
				normal: [
					'bug',
					'dark',
					'dragon',
					'electric',
					'fairy',
					'fighting',
					'fire',
					'flying',
					'grass',
					'ground',
					'ice',
					'normal',
					'poison',
					'psychic',
					'water',
				],
				resisted: ['rock', 'steel'],
			},
			defense: {
				double: ['fighting'],
				immune: ['ghost'],
				normal: [
					'bug',
					'dark',
					'dragon',
					'electric',
					'fairy',
					'fire',
					'flying',
					'grass',
					'ground',
					'ice',
					'normal',
					'poison',
					'psychic',
					'rock',
					'steel',
					'water',
				],
				resisted: [],
			},
		},
	},
	{
		name: TypeEnum.Poison,
		matchup: {
			offense: {
				double: ['fairy', 'grass'],
				immune: ['steel'],
				normal: [
					'bug',
					'dark',
					'dragon',
					'electric',
					'fighting',
					'fire',
					'flying',
					'ice',
					'normal',
					'psychic',
					'water',
				],
				resisted: ['ghost', 'ground', 'poison', 'rock'],
			},
			defense: {
				double: ['ground', 'psychic'],
				immune: [],
				normal: [
					'dark',
					'dragon',
					'electric',
					'fire',
					'flying',
					'ghost',
					'ice',
					'normal',
					'rock',
					'steel',
					'water',
				],
				resisted: ['bug', 'fairy', 'fighting', 'grass', 'poison'],
			},
		},
	},
	{
		name: TypeEnum.Psychic,
		matchup: {
			offense: {
				double: ['fighting', 'poison'],
				immune: ['dark'],
				normal: [
					'bug',
					'dragon',
					'electric',
					'fairy',
					'fire',
					'flying',
					'ghost',
					'grass',
					'ground',
					'ice',
					'normal',
					'rock',
					'water',
				],
				resisted: ['psychic', 'steel'],
			},
			defense: {
				double: ['bug', 'dark', 'ghost'],
				immune: [],
				normal: [
					'dragon',
					'electric',
					'fairy',
					'fire',
					'flying',
					'grass',
					'ground',
					'ice',
					'normal',
					'poison',
					'rock',
					'steel',
					'water',
				],
				resisted: ['fighting', 'psychic'],
			},
		},
	},
	{
		name: TypeEnum.Rock,
		matchup: {
			offense: {
				double: ['bug', 'fire', 'flying', 'ice'],
				immune: [],
				normal: [
					'dark',
					'dragon',
					'electric',
					'fairy',
					'ghost',
					'grass',
					'normal',
					'poison',
					'psychic',
					'rock',
					'water',
				],
				resisted: ['fighting', 'ground', 'steel'],
			},
			defense: {
				double: ['fighting', 'grass', 'ground', 'steel', 'water'],
				immune: [],
				normal: [
					'bug',
					'dark',
					'dragon',
					'electric',
					'fairy',
					'ghost',
					'ice',
					'psychic',
					'rock',
				],
				resisted: ['fire', 'flying', 'normal', 'poison'],
			},
		},
	},
	{
		name: TypeEnum.Steel,
		matchup: {
			offense: {
				double: ['fairy', 'ice', 'rock'],
				immune: [],
				normal: [
					'bug',
					'dark',
					'dragon',
					'fighting',
					'flying',
					'ghost',
					'grass',
					'ground',
					'normal',
					'poison',
					'psychic',
				],
				resisted: ['electric', 'fire', 'steel', 'water'],
			},
			defense: {
				double: ['fighting', 'fire', 'ground'],
				immune: ['poison'],
				normal: ['dark', 'electric', 'ghost', 'water'],
				resisted: [
					'bug',
					'dragon',
					'fairy',
					'flying',
					'grass',
					'ice',
					'normal',
					'psychic',
					'rock',
					'steel',
				],
			},
		},
	},
	{
		name: TypeEnum.Water,
		matchup: {
			offense: {
				double: ['fire', 'ground', 'rock'],
				immune: [],
				normal: [
					'bug',
					'dark',
					'electric',
					'fairy',
					'fighting',
					'flying',
					'ghost',
					'ice',
					'normal',
					'poison',
					'psychic',
					'steel',
				],
				resisted: ['dragon', 'grass', 'water'],
			},
			defense: {
				double: ['electric', 'grass'],
				immune: [],
				normal: [
					'bug',
					'dark',
					'dragon',
					'fairy',
					'fighting',
					'flying',
					'ghost',
					'ground',
					'normal',
					'poison',
					'psychic',
					'rock',
				],
				resisted: ['fire', 'ice', 'steel', 'water'],
			},
		},
	},
];
