import { GraphQLPokemonResponse } from './graphql.service';
import {
	AbilitiesEnum,
	MovesEnum,
	PokemonEnum,
} from '@favware/graphql-pokemon';

export const MockedPokemonData: GraphQLPokemonResponse<'getPokemon'> = {
	getPokemon: {
		key: PokemonEnum.Gengar,
		num: 94,
		baseStatsTotal: 500,
		color: 'Purple',
		height: 1.5,
		sprite: '',
		backSprite: '',
		shinySprite: '',
		shinyBackSprite: '',
		baseForme: '',
		bulbapediaPage: '',
		serebiiPage: '',
		smogonPage: '',
		isEggObtainable: true,
		smogonTier: 'UU',
		species: 'gengar',
		weight: 40.5,
		evYields: {
			attack: 0,
			defense: 0,
			hp: 0,
			specialattack: 3,
			specialdefense: 0,
			speed: 0,
		},
		flavorTexts: [
			{
				game: 'Violet',
				flavor:
					"Hiding in people's shadows at night, it absorbs their heat. The chill it causes makes the victims shake.",
			},
		],
		gender: {
			female: '50%',
			male: '50%',
		},
		abilities: {
			first: {
				name: 'Cursed Body',
				key: AbilitiesEnum.Cursedbody,
				desc: "If this Pokémon is hit by an attack, there is a 30% chance that move gets disabled unless one of the attacker's moves is already disabled.",
				shortDesc:
					'If this Pokémon is hit by an attack, there is a 30% chance that move gets disabled.',
				bulbapediaPage: '',
				pokemonThatHaveThisAbility: [],
				serebiiPage: '',
				smogonPage: '',
			},
			second: null,
			hidden: null,
		},
		types: [
			{
				matchup: {
					attacking: {
						doubleEffectiveTypes: [''],
						doubleResistedTypes: [''],
						effectiveTypes: [''],
						effectlessTypes: [''],
						normalTypes: [''],
						resistedTypes: [''],
					},
					defending: {
						doubleEffectiveTypes: [''],
						doubleResistedTypes: [''],
						effectiveTypes: [''],
						effectlessTypes: [''],
						normalTypes: [''],
						resistedTypes: [''],
					},
				},
				name: 'Ghost',
			},
			{
				matchup: {
					attacking: {
						doubleEffectiveTypes: [''],
						doubleResistedTypes: [''],
						effectiveTypes: [''],
						effectlessTypes: [''],
						normalTypes: [''],
						resistedTypes: [''],
					},
					defending: {
						doubleEffectiveTypes: [''],
						doubleResistedTypes: [''],
						effectiveTypes: [''],
						effectlessTypes: [''],
						normalTypes: [''],
						resistedTypes: [''],
					},
				},
				name: 'Poison',
			},
		],
		baseStats: {
			hp: 60,
			attack: 65,
			defense: 60,
			specialattack: 130,
			specialdefense: 75,
			speed: 110,
		},
		learnsets: {
			generation3: {},
			generation4: {},
			generation5: {},
			generation6: {},
			generation7: {},
			generation8: {
				dreamworldMoves: [],
				eggMoves: [],
				eventMoves: [],
				tmMoves: [
					{
						generation: 9,
						move: {
							key: MovesEnum.Acidspray,
							accuracy: 100,
							basePower: '40',
							category: 'Special',
							desc: "Has a 100% chance to lower the target's Special Defense by 2 stages.",
							name: 'Acid Spray',
							pp: 20,
							priority: 0,
							shortDesc: "100% chance to lower the target's Sp. Def by 2.",
							target: 'Normal',
							type: 'Poison',
							bulbapediaPage: '',
							serebiiPage: '',
							smogonPage: '',
							zMovePower: 100,
						},
					},
				],
				tutorMoves: [],
				virtualTransferMoves: [],
				levelUpMoves: [
					{
						generation: 9,
						move: {
							key: MovesEnum.Confuseray,
							accuracy: 100,
							basePower: '0',
							category: 'Status',
							desc: 'Causes the target to become confused.',
							name: 'Confuse Ray',
							pp: 10,
							priority: 0,
							shortDesc: 'Confuses the target.',
							target: 'Normal',
							type: 'Ghost',
							bulbapediaPage: '',
							serebiiPage: '',
							smogonPage: '',
							zMovePower: 0,
						},
						level: 1,
					},
				],
			},
		},
	},
};

export const MockedMoveData: GraphQLPokemonResponse<'getMove'> = {
	getMove: {
		key: MovesEnum.Disable,
		name: 'Disable',
		shortDesc: "For 4 turns, disables the target's last move used.",
		type: 'Normal',
		basePower: '0',
		pp: 20,
		category: 'Status',
		accuracy: 100,
		priority: 0,
		target: 'Normal',
		desc: "For 4 turns, the target's last move used becomes disabled. Fails if one of the target's moves is already disabled, if the target has not made a move, if the target no longer knows the move, or if the move was a Max or G-Max Move.",
		bulbapediaPage: 'https://bulbapedia.bulbagarden.net/wiki/Disable_(move)',
		contestType: 'Clever',
		isFieldMove: null,
		isGMax: null,
		isNonstandard: null,
		isZ: null,
		maxMovePower: null,
		serebiiPage: 'https://www.serebii.net/attackdex-swsh/disable.shtml',
		smogonPage: 'https://www.smogon.com/dex/ss/moves/disable',
		zMovePower: 0,
	},
};
