export const MockedPokemonData = {
	data: {
		getPokemon: {
			abilities: {
				first: {
					name: 'Cursed Body',
					key: 'cursedbody',
					desc: "If this Pokémon is hit by an attack, there is a 30% chance that move gets disabled unless one of the attacker's moves is already disabled.",
					shortDesc:
						'If this Pokémon is hit by an attack, there is a 30% chance that move gets disabled.',
				},
				second: null,
				hidden: null,
			},
			key: 'gengar',
			num: 94,
			types: [
				{
					name: 'Ghost',
				},
				{
					name: 'Poison',
				},
			],
			baseStats: {
				hp: 60,
				attack: 65,
				defense: 60,
				specialattack: 130,
				specialdefense: 75,
				speed: 110,
			},
			learnsets: {
				generation8: {
					dreamworldMoves: [],
					eggMoves: [],
					eventMoves: [],
					tmMoves: [
						{
							generation: 9,
							move: {
								key: 'acidspray',
								accuracy: 100,
								basePower: '40',
								category: 'Special',
								desc: "Has a 100% chance to lower the target's Special Defense by 2 stages.",
								name: 'Acid Spray',
								pp: 20,
								priority: 0,
								shortDesc: "100% chance to lower the target's Sp. Def by 2.",
								target: 'Normal',
								type: 'Poison',
							},
						},
						{
							generation: 9,
							move: {
								key: 'bodyslam',
								accuracy: 100,
								basePower: '85',
								category: 'Physical',
								desc: 'Has a 30% chance to paralyze the target. Damage doubles and no accuracy check is done if the target has used Minimize while active.',
								name: 'Body Slam',
								pp: 15,
								priority: 0,
								shortDesc: '30% chance to paralyze the target.',
								target: 'Normal',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'brickbreak',
								accuracy: 100,
								basePower: '75',
								category: 'Physical',
								desc: "If this attack does not miss, the effects of Reflect, Light Screen, and Aurora Veil end for the target's side of the field before damage is calculated.",
								name: 'Brick Break',
								pp: 15,
								priority: 0,
								shortDesc: 'Destroys screens, unless the target is immune.',
								target: 'Normal',
								type: 'Fighting',
							},
						},
						{
							generation: 9,
							move: {
								key: 'confuseray',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'Causes the target to become confused.',
								name: 'Confuse Ray',
								pp: 10,
								priority: 0,
								shortDesc: 'Confuses the target.',
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'darkpulse',
								accuracy: 100,
								basePower: '80',
								category: 'Special',
								desc: 'Has a 20% chance to make the target flinch.',
								name: 'Dark Pulse',
								pp: 15,
								priority: 0,
								shortDesc: '20% chance to make the target flinch.',
								target: 'Any',
								type: 'Dark',
							},
						},
						{
							generation: 9,
							move: {
								key: 'dazzlinggleam',
								accuracy: 100,
								basePower: '80',
								category: 'Special',
								desc: 'No additional effect.',
								name: 'Dazzling Gleam',
								pp: 10,
								priority: 0,
								shortDesc: 'No additional effect. Hits adjacent foes.',
								target: 'Adjacent Foes',
								type: 'Fairy',
							},
						},
						{
							generation: 9,
							move: {
								key: 'drainpunch',
								accuracy: 100,
								basePower: '75',
								category: 'Physical',
								desc: 'The user recovers 1/2 the HP lost by the target, rounded half up. If Big Root is held by the user, the HP recovered is 1.3x normal, rounded half down.',
								name: 'Drain Punch',
								pp: 10,
								priority: 0,
								shortDesc: 'User recovers 50% of the damage dealt.',
								target: 'Normal',
								type: 'Fighting',
							},
						},
						{
							generation: 9,
							move: {
								key: 'encore',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'For its next 3 turns, the target is forced to repeat its last move used. If the affected move runs out of PP, the effect ends. Fails if the target is already under this effect, if it has not made a move, if the move has 0 PP, if the move is Assist, Copycat, Dynamax Cannon, Encore, Me First, Metronome, Mimic, Mirror Move, Nature Power, Sketch, Sleep Talk, Struggle, or Transform, or if the target is Dynamaxed.',
								name: 'Encore',
								pp: 5,
								priority: 0,
								shortDesc: 'Target repeats its last move for its next 3 turns.',
								target: 'Normal',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'endure',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "The user will survive attacks made by other Pokémon during this turn with at least 1 HP. This move has a 1/X chance of being successful, where X starts at 1 and triples each time this move is successfully used. X resets to 1 if this move fails, if the user's last move used is not Baneful Bunker, Detect, Endure, King's Shield, Max Guard, Obstruct, Protect, Quick Guard, Spiky Shield, or Wide Guard, or if it was one of those moves and the user's protection was broken. Fails if the user moves last this turn.",
								name: 'Endure',
								pp: 10,
								priority: 4,
								shortDesc:
									'User survives attacks this turn with at least 1 HP.',
								target: 'Self',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'energyball',
								accuracy: 100,
								basePower: '90',
								category: 'Special',
								desc: "Has a 10% chance to lower the target's Special Defense by 1 stage.",
								name: 'Energy Ball',
								pp: 10,
								priority: 0,
								shortDesc: "10% chance to lower the target's Sp. Def by 1.",
								target: 'Normal',
								type: 'Grass',
							},
						},
						{
							generation: 9,
							move: {
								key: 'facade',
								accuracy: 100,
								basePower: '70',
								category: 'Physical',
								desc: "Power doubles if the user is burned, paralyzed, or poisoned. The physical damage halving effect from the user's burn is ignored.",
								name: 'Facade',
								pp: 20,
								priority: 0,
								shortDesc: 'Power doubles if user is burn/poison/paralyzed.',
								target: 'Normal',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'firepunch',
								accuracy: 100,
								basePower: '75',
								category: 'Physical',
								desc: 'Has a 10% chance to burn the target.',
								name: 'Fire Punch',
								pp: 15,
								priority: 0,
								shortDesc: '10% chance to burn the target.',
								target: 'Normal',
								type: 'Fire',
							},
						},
						{
							generation: 9,
							move: {
								key: 'fling',
								accuracy: 100,
								basePower: '0',
								category: 'Physical',
								desc: "The power of this move is based on the user's held item. The held item is lost and it activates for the target if applicable. If there is no target or the target avoids this move by protecting itself, the user's held item is still lost. The user can regain a thrown item with Recycle or the Harvest Ability. Fails if the user has no held item, if the held item cannot be thrown, if the user is under the effect of Embargo or Magic Room, or if the user has the Klutz Ability.",
								name: 'Fling',
								pp: 10,
								priority: 0,
								shortDesc:
									"Flings the user's item at the target. Power varies.",
								target: 'Normal',
								type: 'Dark',
							},
						},
						{
							generation: 9,
							move: {
								key: 'focusblast',
								accuracy: 70,
								basePower: '120',
								category: 'Special',
								desc: "Has a 10% chance to lower the target's Special Defense by 1 stage.",
								name: 'Focus Blast',
								pp: 5,
								priority: 0,
								shortDesc: "10% chance to lower the target's Sp. Def by 1.",
								target: 'Normal',
								type: 'Fighting',
							},
						},
						{
							generation: 9,
							move: {
								key: 'foulplay',
								accuracy: 100,
								basePower: '95',
								category: 'Physical',
								desc: "Damage is calculated using the target's Attack stat, including stat stage changes. The user's Ability, item, and burn are used as normal.",
								name: 'Foul Play',
								pp: 15,
								priority: 0,
								shortDesc: "Uses target's Attack stat in damage calculation.",
								target: 'Normal',
								type: 'Dark',
							},
						},
						{
							generation: 9,
							move: {
								key: 'gigadrain',
								accuracy: 100,
								basePower: '75',
								category: 'Special',
								desc: 'The user recovers 1/2 the HP lost by the target, rounded half up. If Big Root is held by the user, the HP recovered is 1.3x normal, rounded half down.',
								name: 'Giga Drain',
								pp: 10,
								priority: 0,
								shortDesc: 'User recovers 50% of the damage dealt.',
								target: 'Normal',
								type: 'Grass',
							},
						},
						{
							generation: 9,
							move: {
								key: 'gigaimpact',
								accuracy: 90,
								basePower: '150',
								category: 'Physical',
								desc: 'If this move is successful, the user must recharge on the following turn and cannot select a move.',
								name: 'Giga Impact',
								pp: 5,
								priority: 0,
								shortDesc: 'User cannot move next turn.',
								target: 'Normal',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'gunkshot',
								accuracy: 80,
								basePower: '120',
								category: 'Physical',
								desc: 'Has a 30% chance to poison the target.',
								name: 'Gunk Shot',
								pp: 5,
								priority: 0,
								shortDesc: '30% chance to poison the target.',
								target: 'Normal',
								type: 'Poison',
							},
						},
						{
							generation: 9,
							move: {
								key: 'hex',
								accuracy: 100,
								basePower: '65',
								category: 'Special',
								desc: 'Power doubles if the target has a non-volatile status condition.',
								name: 'Hex',
								pp: 10,
								priority: 0,
								shortDesc: 'Power doubles if the target has a status ailment.',
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'hyperbeam',
								accuracy: 90,
								basePower: '150',
								category: 'Special',
								desc: 'If this move is successful, the user must recharge on the following turn and cannot select a move.',
								name: 'Hyper Beam',
								pp: 5,
								priority: 0,
								shortDesc: 'User cannot move next turn.',
								target: 'Normal',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'icepunch',
								accuracy: 100,
								basePower: '75',
								category: 'Physical',
								desc: 'Has a 10% chance to freeze the target.',
								name: 'Ice Punch',
								pp: 15,
								priority: 0,
								shortDesc: '10% chance to freeze the target.',
								target: 'Normal',
								type: 'Ice',
							},
						},
						{
							generation: 9,
							move: {
								key: 'icywind',
								accuracy: 95,
								basePower: '55',
								category: 'Special',
								desc: "Has a 100% chance to lower the target's Speed by 1 stage.",
								name: 'Icy Wind',
								pp: 15,
								priority: 0,
								shortDesc: '100% chance to lower the foe(s) Speed by 1.',
								target: 'Adjacent Foes',
								type: 'Ice',
							},
						},
						{
							generation: 9,
							move: {
								key: 'imprison',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'The user prevents all opposing Pokémon from using any moves that the user also knows as long as the user remains active.',
								name: 'Imprison',
								pp: 10,
								priority: 0,
								shortDesc: 'No foe can use any move known by the user.',
								target: 'Self',
								type: 'Psychic',
							},
						},
						{
							generation: 9,
							move: {
								key: 'metronome',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "A random move is selected for use, other than After You, Apple Acid, Armor Cannon, Assist, Astral Barrage, Aura Wheel, Baneful Bunker, Beak Blast, Behemoth Bash, Behemoth Blade, Belch, Bestow, Blazing Torque, Body Press, Branch Poke, Breaking Swipe, Celebrate, Chatter, Chilling Water, Chilly Reception, Clangorous Soul, Collision Course, Combat Torque, Comeuppance, Copycat, Counter, Covet, Crafty Shield, Decorate, Destiny Bond, Detect, Diamond Storm, Doodle, Double Iron Bash, Double Shock, Dragon Ascent, Dragon Energy, Drum Beating, Dynamax Cannon, Electro Drift, Endure, Eternabeam, False Surrender, Feint, Fiery Wrath, Fillet Away, Fleur Cannon, Focus Punch, Follow Me, Freeze Shock, Freezing Glare, Glacial Lance, Grav Apple, Helping Hand, Hold Hands, Hyper Drill, Hyperspace Fury, Hyperspace Hole, Ice Burn, Instruct, Jet Punch, Jungle Healing, King's Shield, Life Dew, Light of Ruin, Magical Torque, Make It Rain, Mat Block, Me First, Meteor Assault, Metronome, Mimic, Mind Blown, Mirror Coat, Mirror Move, Moongeist Beam, Nature Power, Nature's Madness, Noxious Torque, Obstruct, Order Up, Origin Pulse, Overdrive, Photon Geyser, Plasma Fists, Population Bomb, Pounce, Power Shift, Precipice Blades, Protect, Pyro Ball, Quash, Quick Guard, Rage Fist, Rage Powder, Raging Bull, Raging Fury, Relic Song, Revival Blessing, Ruination, Salt Cure, Secret Sword, Shed Tail, Shell Trap, Silk Trap, Sketch, Sleep Talk, Snap Trap, Snarl, Snatch, Snore, Snowscape, Spectral Thief, Spicy Extract, Spiky Shield, Spirit Break, Spotlight, Springtide Storm, Steam Eruption, Steel Beam, Strange Steam, Struggle, Sunsteel Strike, Surging Strikes, Switcheroo, Techno Blast, Thief, Thousand Arrows, Thousand Waves, Thunder Cage, Thunderous Kick, Tidy Up, Trailblaze, Transform, Trick, Twin Beam, V-create, Wicked Blow, Wicked Torque, or Wide Guard.",
								name: 'Metronome',
								pp: 10,
								priority: 0,
								shortDesc: 'Picks a random move.',
								target: 'Self',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'nastyplot',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "Raises the user's Special Attack by 2 stages.",
								name: 'Nasty Plot',
								pp: 20,
								priority: 0,
								shortDesc: "Raises the user's Sp. Atk by 2.",
								target: 'Self',
								type: 'Dark',
							},
						},
						{
							generation: 9,
							move: {
								key: 'nightshade',
								accuracy: 100,
								basePower: 'level',
								category: 'Special',
								desc: "Deals damage to the target equal to the user's level.",
								name: 'Night Shade',
								pp: 15,
								priority: 0,
								shortDesc: "Does damage equal to the user's level.",
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'phantomforce',
								accuracy: 100,
								basePower: '90',
								category: 'Physical',
								desc: "If this move is successful, it breaks through the target's Baneful Bunker, Detect, King's Shield, Protect, or Spiky Shield for this turn, allowing other Pokémon to attack the target normally. If the target's side is protected by Crafty Shield, Mat Block, Quick Guard, or Wide Guard, that protection is also broken for this turn and other Pokémon may attack the target's side normally. This attack charges on the first turn and executes on the second. On the first turn, the user avoids all attacks. If the user is holding a Power Herb, the move completes in one turn.",
								name: 'Phantom Force',
								pp: 10,
								priority: 0,
								shortDesc: 'Disappears turn 1. Hits turn 2. Breaks protection.',
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'poisonjab',
								accuracy: 100,
								basePower: '80',
								category: 'Physical',
								desc: 'Has a 30% chance to poison the target.',
								name: 'Poison Jab',
								pp: 20,
								priority: 0,
								shortDesc: '30% chance to poison the target.',
								target: 'Normal',
								type: 'Poison',
							},
						},
						{
							generation: 9,
							move: {
								key: 'protect',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "The user is protected from most attacks made by other Pokémon during this turn. This move has a 1/X chance of being successful, where X starts at 1 and triples each time this move is successfully used. X resets to 1 if this move fails, if the user's last move used is not Baneful Bunker, Detect, Endure, King's Shield, Max Guard, Obstruct, Protect, Quick Guard, Spiky Shield, or Wide Guard, or if it was one of those moves and the user's protection was broken. Fails if the user moves last this turn.",
								name: 'Protect',
								pp: 10,
								priority: 4,
								shortDesc: 'Prevents moves from affecting the user this turn.',
								target: 'Self',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'psychic',
								accuracy: 100,
								basePower: '90',
								category: 'Special',
								desc: "Has a 10% chance to lower the target's Special Defense by 1 stage.",
								name: 'Psychic',
								pp: 10,
								priority: 0,
								shortDesc: "10% chance to lower the target's Sp. Def by 1.",
								target: 'Normal',
								type: 'Psychic',
							},
						},
						{
							generation: 9,
							move: {
								key: 'raindance',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'For 5 turns, the weather becomes Rain Dance. The damage of Water-type attacks is multiplied by 1.5 and the damage of Fire-type attacks is multiplied by 0.5 during the effect. Lasts for 8 turns if the user is holding Damp Rock. Fails if the current weather is Rain Dance.',
								name: 'Rain Dance',
								pp: 5,
								priority: 0,
								shortDesc: 'For 5 turns, heavy rain powers Water moves.',
								target: 'All',
								type: 'Water',
							},
						},
						{
							generation: 9,
							move: {
								key: 'rest',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'The user falls asleep for the next two turns and restores all of its HP, curing itself of any non-volatile status condition in the process. Fails if the user has full HP, is already asleep, or if another effect is preventing sleep.',
								name: 'Rest',
								pp: 5,
								priority: 0,
								shortDesc: 'User sleeps 2 turns and restores HP and status.',
								target: 'Self',
								type: 'Psychic',
							},
						},
						{
							generation: 9,
							move: {
								key: 'scaryface',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "Lowers the target's Speed by 2 stages.",
								name: 'Scary Face',
								pp: 10,
								priority: 0,
								shortDesc: "Lowers the target's Speed by 2.",
								target: 'Normal',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'shadowball',
								accuracy: 100,
								basePower: '80',
								category: 'Special',
								desc: "Has a 20% chance to lower the target's Special Defense by 1 stage.",
								name: 'Shadow Ball',
								pp: 15,
								priority: 0,
								shortDesc: "20% chance to lower the target's Sp. Def by 1.",
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'shadowclaw',
								accuracy: 100,
								basePower: '70',
								category: 'Physical',
								desc: 'Has a higher chance for a critical hit.',
								name: 'Shadow Claw',
								pp: 15,
								priority: 0,
								shortDesc: 'High critical hit ratio.',
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'skillswap',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "The user swaps its Ability with the target's Ability. Fails if either the user or the target's Ability is As One, Battle Bond, Comatose, Disguise, Gulp Missile, Hunger Switch, Ice Face, Illusion, Multitype, Neutralizing Gas, Power Construct, RKS System, Schooling, Shields Down, Stance Change, Wonder Guard, or Zen Mode.",
								name: 'Skill Swap',
								pp: 10,
								priority: 0,
								shortDesc: 'The user and the target trade Abilities.',
								target: 'Normal',
								type: 'Psychic',
							},
						},
						{
							generation: 9,
							move: {
								key: 'sleeptalk',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "One of the user's known moves, besides this move, is selected for use at random. Fails if the user is not asleep. The selected move does not have PP deducted from it, and can currently have 0 PP. This move cannot select Assist, Beak Blast, Belch, Bide, Celebrate, Chatter, Copycat, Dynamax Cannon, Focus Punch, Hold Hands, Me First, Metronome, Mimic, Mirror Move, Nature Power, Shell Trap, Sketch, Sleep Talk, Struggle, Uproar, any two-turn move, or any Max Move.",
								name: 'Sleep Talk',
								pp: 10,
								priority: 0,
								shortDesc: 'User must be asleep. Uses another known move.',
								target: 'Self',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'sludgebomb',
								accuracy: 100,
								basePower: '90',
								category: 'Special',
								desc: 'Has a 30% chance to poison the target.',
								name: 'Sludge Bomb',
								pp: 10,
								priority: 0,
								shortDesc: '30% chance to poison the target.',
								target: 'Normal',
								type: 'Poison',
							},
						},
						{
							generation: 9,
							move: {
								key: 'substitute',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'The user takes 1/4 of its maximum HP, rounded down, and puts it into a substitute to take its place in battle. The substitute is removed once enough damage is inflicted on it, or if the user switches out or faints. Baton Pass can be used to transfer the substitute to an ally, and the substitute will keep its remaining HP. Until the substitute is broken, it receives damage from all attacks made by other Pokémon and shields the user from status effects and stat stage changes caused by other Pokémon. Sound-based moves and Pokémon with the Infiltrator Ability ignore substitutes. The user still takes normal damage from weather and status effects while behind its substitute. If the substitute breaks during a multi-hit attack, the user will take damage from any remaining hits. If a substitute is created while the user is trapped by a binding move, the binding effect ends immediately. Fails if the user does not have enough HP remaining to create a substitute without fainting, or if it already has a substitute.',
								name: 'Substitute',
								pp: 10,
								priority: 0,
								shortDesc: 'User takes 1/4 its max HP to put in a substitute.',
								target: 'Self',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'sunnyday',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'For 5 turns, the weather becomes Sunny Day. The damage of Fire-type attacks is multiplied by 1.5 and the damage of Water-type attacks is multiplied by 0.5 during the effect. Lasts for 8 turns if the user is holding Heat Rock. Fails if the current weather is Sunny Day.',
								name: 'Sunny Day',
								pp: 5,
								priority: 0,
								shortDesc: 'For 5 turns, intense sunlight powers Fire moves.',
								target: 'All',
								type: 'Fire',
							},
						},
						{
							generation: 9,
							move: {
								key: 'taunt',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'Prevents the target from using non-damaging moves for its next three turns. Pokémon with the Oblivious Ability or protected by the Aroma Veil Ability are immune.',
								name: 'Taunt',
								pp: 20,
								priority: 0,
								shortDesc: "Target can't use status moves its next 3 turns.",
								target: 'Normal',
								type: 'Dark',
							},
						},
						{
							generation: 9,
							move: {
								key: 'terablast',
								accuracy: 100,
								basePower: '80',
								category: 'Special',
								desc: "If the user is Terastallized, this move becomes a physical attack if the user's Attack is greater than its Special Attack, including stat stage changes, and it becomes the same its the user's Tera Type.",
								name: 'Tera Blast',
								pp: 10,
								priority: 0,
								shortDesc:
									'If Terastallized: Phys. if Atk > SpA & Type = Tera Type.',
								target: 'Normal',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'thief',
								accuracy: 100,
								basePower: '60',
								category: 'Physical',
								desc: "If this attack was successful and the user has not fainted, it steals the target's held item if the user is not holding one. The target's item is not stolen if it is a Mail or Z-Crystal, or if the target is a Kyogre holding a Blue Orb, a Groudon holding a Red Orb, a Giratina holding a Griseous Orb, an Arceus holding a Plate, a Genesect holding a Drive, a Silvally holding a Memory, or a Pokémon that can Mega Evolve holding the Mega Stone for its species. Items lost to this move cannot be regained with Recycle or the Harvest Ability.",
								name: 'Thief',
								pp: 25,
								priority: 0,
								shortDesc: "If the user has no item, it steals the target's.",
								target: 'Normal',
								type: 'Dark',
							},
						},
						{
							generation: 9,
							move: {
								key: 'thunder',
								accuracy: 70,
								basePower: '110',
								category: 'Special',
								desc: "Has a 30% chance to paralyze the target. This move can hit a target using Bounce, Fly, or Sky Drop, or is under the effect of Sky Drop. If the weather is Primordial Sea or Rain Dance, this move does not check accuracy. If the weather is Desolate Land or Sunny Day, this move's accuracy is 50%. If this move is used against a Pokémon holding Utility Umbrella, this move's accuracy remains at 70%.",
								name: 'Thunder',
								pp: 10,
								priority: 0,
								shortDesc: "30% chance to paralyze. Can't miss in rain.",
								target: 'Normal',
								type: 'Electric',
							},
						},
						{
							generation: 9,
							move: {
								key: 'thunderbolt',
								accuracy: 100,
								basePower: '90',
								category: 'Special',
								desc: 'Has a 10% chance to paralyze the target.',
								name: 'Thunderbolt',
								pp: 15,
								priority: 0,
								shortDesc: '10% chance to paralyze the target.',
								target: 'Normal',
								type: 'Electric',
							},
						},
						{
							generation: 9,
							move: {
								key: 'thunderpunch',
								accuracy: 100,
								basePower: '75',
								category: 'Physical',
								desc: 'Has a 10% chance to paralyze the target.',
								name: 'Thunder Punch',
								pp: 15,
								priority: 0,
								shortDesc: '10% chance to paralyze the target.',
								target: 'Normal',
								type: 'Electric',
							},
						},
						{
							generation: 9,
							move: {
								key: 'thunderwave',
								accuracy: 90,
								basePower: '0',
								category: 'Status',
								desc: 'Paralyzes the target. This move does not ignore type immunity.',
								name: 'Thunder Wave',
								pp: 20,
								priority: 0,
								shortDesc: 'Paralyzes the target.',
								target: 'Normal',
								type: 'Electric',
							},
						},
						{
							generation: 9,
							move: {
								key: 'toxicspikes',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'Sets up a hazard on the opposing side of the field, poisoning each opposing Pokémon that switches in, unless it is a Flying-type Pokémon or has the Levitate Ability. Can be used up to two times before failing. Opposing Pokémon become poisoned with one layer and badly poisoned with two layers. Can be removed from the opposing side if any opposing Pokémon uses Rapid Spin or Defog successfully, is hit by Defog, or a grounded Poison-type Pokémon switches in. Safeguard prevents the opposing party from being poisoned on switch-in, but a substitute does not.',
								name: 'Toxic Spikes',
								pp: 20,
								priority: 0,
								shortDesc: 'Poisons grounded foes on switch-in. Max 2 layers.',
								target: "Foe's Side",
								type: 'Poison',
							},
						},
						{
							generation: 9,
							move: {
								key: 'trick',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "The user swaps its held item with the target's held item. Fails if either the user or the target is holding a Mail or Z-Crystal, if neither is holding an item, if the user is trying to give or take a Mega Stone to or from the species that can Mega Evolve with it, or if the user is trying to give or take a Blue Orb, a Red Orb, a Griseous Orb, a Plate, a Drive, or a Memory to or from a Kyogre, a Groudon, a Giratina, an Arceus, a Genesect, or a Silvally, respectively. The target is immune to this move if it has the Sticky Hold Ability.",
								name: 'Trick',
								pp: 10,
								priority: 0,
								shortDesc: "User switches its held item with the target's.",
								target: 'Normal',
								type: 'Psychic',
							},
						},
						{
							generation: 9,
							move: {
								key: 'trickroom',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "For 5 turns, the Speed of every Pokémon is recalculated for the purposes of determining turn order. During the effect, each Pokémon's Speed is considered to be (10000 - its normal Speed), and if this value is greater than 8191, 8192 is subtracted from it. If this move is used during the effect, the effect ends.",
								name: 'Trick Room',
								pp: 5,
								priority: -7,
								shortDesc: 'Goes last. For 5 turns, turn order is reversed.',
								target: 'All',
								type: 'Psychic',
							},
						},
						{
							generation: 9,
							move: {
								key: 'venoshock',
								accuracy: 100,
								basePower: '65',
								category: 'Special',
								desc: 'Power doubles if the target is poisoned.',
								name: 'Venoshock',
								pp: 10,
								priority: 0,
								shortDesc: 'Power doubles if the target is poisoned.',
								target: 'Normal',
								type: 'Poison',
							},
						},
						{
							generation: 9,
							move: {
								key: 'willowisp',
								accuracy: 85,
								basePower: '0',
								category: 'Status',
								desc: 'Burns the target.',
								name: 'Will-O-Wisp',
								pp: 15,
								priority: 0,
								shortDesc: 'Burns the target.',
								target: 'Normal',
								type: 'Fire',
							},
						},
					],
					tutorMoves: [],
					virtualTransferMoves: [],
					levelUpMoves: [
						{
							generation: 9,
							move: {
								key: 'confuseray',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'Causes the target to become confused.',
								name: 'Confuse Ray',
								pp: 10,
								priority: 0,
								shortDesc: 'Confuses the target.',
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'curse',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "If the user is not a Ghost type, lowers the user's Speed by 1 stage and raises the user's Attack and Defense by 1 stage. If the user is a Ghost type, the user loses 1/2 of its maximum HP, rounded down and even if it would cause fainting, in exchange for the target losing 1/4 of its maximum HP, rounded down, at the end of each turn while it is active. If the target uses Baton Pass, the replacement will continue to be affected. Fails if there is no target or if the target is already affected.",
								name: 'Curse',
								pp: 10,
								priority: 0,
								shortDesc: 'Curses if Ghost, else -1 Spe, +1 Atk, +1 Def.',
								target: 'Random',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'darkpulse',
								accuracy: 100,
								basePower: '80',
								category: 'Special',
								desc: 'Has a 20% chance to make the target flinch.',
								name: 'Dark Pulse',
								pp: 15,
								priority: 0,
								shortDesc: '20% chance to make the target flinch.',
								target: 'Any',
								type: 'Dark',
							},
						},
						{
							generation: 9,
							move: {
								key: 'destinybond',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "Until the user's next move, if an opposing Pokémon's attack knocks the user out, that Pokémon faints as well, unless the attack was Doom Desire or Future Sight. Fails if the user used this move successfully as its last move, disregarding moves used through the Dancer Ability.",
								name: 'Destiny Bond',
								pp: 5,
								priority: 0,
								shortDesc:
									'If an opponent knocks out the user, it also faints.',
								target: 'Self',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'dreameater',
								accuracy: 100,
								basePower: '100',
								category: 'Special',
								desc: 'The target is unaffected by this move unless it is asleep. The user recovers 1/2 the HP lost by the target, rounded half up. If Big Root is held by the user, the HP recovered is 1.3x normal, rounded half down.',
								name: 'Dream Eater',
								pp: 15,
								priority: 0,
								shortDesc: 'User gains 1/2 HP inflicted. Sleeping target only.',
								target: 'Normal',
								type: 'Psychic',
							},
						},
						{
							generation: 9,
							move: {
								key: 'hex',
								accuracy: 100,
								basePower: '65',
								category: 'Special',
								desc: 'Power doubles if the target has a non-volatile status condition.',
								name: 'Hex',
								pp: 10,
								priority: 0,
								shortDesc: 'Power doubles if the target has a status ailment.',
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'hypnosis',
								accuracy: 60,
								basePower: '0',
								category: 'Status',
								desc: 'Causes the target to fall asleep.',
								name: 'Hypnosis',
								pp: 20,
								priority: 0,
								shortDesc: 'Causes the target to fall asleep.',
								target: 'Normal',
								type: 'Psychic',
							},
						},
						{
							generation: 9,
							move: {
								key: 'lick',
								accuracy: 100,
								basePower: '30',
								category: 'Physical',
								desc: 'Has a 30% chance to paralyze the target.',
								name: 'Lick',
								pp: 30,
								priority: 0,
								shortDesc: '30% chance to paralyze the target.',
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'meanlook',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: 'Prevents the target from switching out. The target can still switch out if it is holding Shed Shell or uses Baton Pass, Flip Turn, Parting Shot, Teleport, U-turn, or Volt Switch. If the target leaves the field using Baton Pass, the replacement will remain trapped. The effect ends if the user leaves the field.',
								name: 'Mean Look',
								pp: 5,
								priority: 0,
								shortDesc: 'Prevents the target from switching out.',
								target: 'Adjacent Foes',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'nightshade',
								accuracy: 100,
								basePower: 'level',
								category: 'Special',
								desc: "Deals damage to the target equal to the user's level.",
								name: 'Night Shade',
								pp: 15,
								priority: 0,
								shortDesc: "Does damage equal to the user's level.",
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'payback',
								accuracy: 100,
								basePower: '50',
								category: 'Physical',
								desc: 'Power doubles if the user moves after the target this turn, including actions taken through Instruct or the Dancer Ability. Switching in does not count as an action.',
								name: 'Payback',
								pp: 10,
								priority: 0,
								shortDesc: 'Power doubles if the user moves after the target.',
								target: 'Normal',
								type: 'Dark',
							},
						},
						{
							generation: 9,
							move: {
								key: 'perishsong',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "Each active Pokémon receives a perish count of 4 if it doesn't already have a perish count. At the end of each turn including the turn used, the perish count of all active Pokémon lowers by 1 and Pokémon faint if the number reaches 0. The perish count is removed from Pokémon that switch out. If a Pokémon uses Baton Pass while it has a perish count, the replacement will gain the perish count and continue to count down.",
								name: 'Perish Song',
								pp: 5,
								priority: 0,
								shortDesc: 'All active Pokémon will faint in 3 turns.',
								target: 'All',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'reflecttype',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "Causes the user's types to become the same as the current types of the target. If the target's current types include typeless and a non-added type, typeless is ignored. If the target's current types include typeless and an added type from Forest's Curse or Trick-or-Treat, typeless is copied as the Normal type instead. Fails if the user is an Arceus or a Silvally, or if the target's current type is typeless alone.",
								name: 'Reflect Type',
								pp: 15,
								priority: 0,
								shortDesc: 'User becomes the same type as the target.',
								target: 'Normal',
								type: 'Normal',
							},
						},
						{
							generation: 9,
							move: {
								key: 'shadowball',
								accuracy: 100,
								basePower: '80',
								category: 'Special',
								desc: "Has a 20% chance to lower the target's Special Defense by 1 stage.",
								name: 'Shadow Ball',
								pp: 15,
								priority: 0,
								shortDesc: "20% chance to lower the target's Sp. Def by 1.",
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'shadowpunch',
								accuracy: 100,
								basePower: '60',
								category: 'Physical',
								desc: 'This move does not check accuracy.',
								name: 'Shadow Punch',
								pp: 20,
								priority: 0,
								shortDesc: 'This move does not check accuracy.',
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'spite',
								accuracy: 100,
								basePower: '0',
								category: 'Status',
								desc: "Causes the target's last move used to lose 4 PP. Fails if the target has not made a move, if the move has 0 PP, or if it no longer knows the move.",
								name: 'Spite',
								pp: 10,
								priority: 0,
								shortDesc: "Lowers the PP of the target's last move by 4.",
								target: 'Normal',
								type: 'Ghost',
							},
						},
						{
							generation: 9,
							move: {
								key: 'suckerpunch',
								accuracy: 100,
								basePower: '70',
								category: 'Physical',
								desc: 'Fails if the target did not select a physical attack, special attack, or Me First for use this turn, or if the target moves before the user.',
								name: 'Sucker Punch',
								pp: 5,
								priority: 1,
								shortDesc:
									'Usually goes first. Fails if target is not attacking.',
								target: 'Normal',
								type: 'Dark',
							},
						},
					],
				},
			},
		},
	},
};
